INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (1,'Dynamic binding between objects'),
	 (1,'The applet makes the Java code secure and portable'),
	 (1,'Use of exception handling'),
	 (2,'Dynamic'),
	 (2,'Architecture Neutral'),
	 (2,'Object-oriented'),
	 (3,'JVM'),
	 (3,'JRE'),
	 (3,'JDK'),
	 (4,'char ca = ''tea'';');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (4,'char cr = ȣ;'),
	 (4,'char cc = ''itea'';'),
	 (5,'long'),
	 (5,'object'),
	 (5,'void'),
	 (6,'javap tool'),
	 (6,'javaw command'),
	 (6,'javah command'),
	 (7,'new List(true, 3)'),
	 (7,'new List(false, 3)');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (7,'new List(3, false)'),
	 (8,'getClass()'),
	 (8,'toString()'),
	 (8,'intern()'),
	 (9,'Serialization'),
	 (9,'Abstraction'),
	 (9,'Multi-threading'),
	 (10,'java.lang package'),
	 (10,'java.awt package'),
	 (10,'java.io package');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (11,'.js'),
	 (11,'.txt'),
	 (11,'.class'),
	 (12,'Servlets can use the full functionality of the Java class libraries'),
	 (12,'Servlets execute within the address space of web server'),
	 (12,'Servlets are platform-independent because they are written in java'),
	 (13,' 0 to 34535'),
	 (13,'-128 to 127'),
	 (13,'0 to 256'),
	 (14,'Protected');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (14,'Public '),
	 (14,'Private'),
	 (15,'more classes inheriting from one super class'),
	 (15,'more classes inheriting from more super classes'),
	 (15,'None of the above'),
	 (16,'static'),
	 (16,'const'),
	 (16,'abstract'),
	 (17,'Import statement, package declaration, class declaration'),
	 (17,'Import statement, class declaration, package declaration');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (17,'Class declaration, import statement, package declaration'),
	 (18,'Compiler will choose randomly'),
	 (18,'Interpreter will choose randomly'),
	 (18,'Superclass'),
	 (19,'In java it is not easy to write C-like so called procedural programs'),
	 (19,'In java language objects have to be manipulated'),
	 (20,'In java it is not easy to write C-like so called procedural programs'),
	 (20,'In java language objects have to be manipulated'),
	 (19,'Java is a fully object oriented language with strong support '),
	 (20,'Java is a fully object oriented language with strong support');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (28,'A simple class'),
	 (28,'Static class'),
	 (28,'None of the mentioned'),
	 (29,'Selection statements'),
	 (29,'Loop Statements'),
	 (29,'Pause Statement'),
	 (30,'32'),
	 (30,'16'),
	 (30,'128'),
	 (31,'Function');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (31,'Fun'),
	 (31,'Define'),
	 (32,' factorial()'),
	 (32,'seed()'),
	 (32,'sqrt()'),
	 (33,'Object'),
	 (33,'Attribute'),
	 (33,'Argument'),
	 (34,'raise'),
	 (34,'try');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (34,'with'),
	 (35,'raise'),
	 (35,'try'),
	 (35,'with'),
	 (36,'Division'),
	 (36,'Subtraction'),
	 (36,'Power'),
	 (37,'Right to Left'),
	 (37,'Can’t say'),
	 (37,'None of the mentioned');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (38,' lower case'),
	 (38,'UPPER CASE'),
	 (38,'Capitalized'),
	 (39,'no'),
	 (39,'machine dependent'),
	 (39,'none of the mentioned'),
	 (40,'Steve Jobs'),
	 (40,'James Gosling'),
	 (40,'Rasmus Lerdorf'),
	 (41,'int number;');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (41,'float rate;'),
	 (41,'nt variable_count;'),
	 (42,'UpperCase letters'),
	 (42,'CamelCase letters'),
	 (42,'None of the mentioned'),
	 (43,'Variable can be of any length'),
	 (44,'int my_num = 100,000;'),
	 (44,'int my num = 1000;'),
	 (44,'int $my_num = 10000;'),
	 (45,'true');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (45,'friend'),
	 (45,'export'),
	 (46,'The basic data type of C'),
	 (46,' Qualifier'),
	 (46,'All of the mentioned'),
	 (47,'char *str;'),
	 (47,'float str = 3e2;'),
	 (47,'Both String str; & float str = 3e2;'),
	 (48,'immutable'),
	 (48,'mutable');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (48,'volatile'),
	 (49,'True or False'),
	 (49,'0 if an expression is false and any positive number if an expression is true'),
	 (49,'None of the mentioned'),
	 (50,'print(''Hello World'');'),
	 (50,'echo(''Hello World'');'),
	 (50,'Console.WriteLine(''Hello World'');'),
	 (51,'16 bit'),
	 (51,'32 bit'),
	 (51,'64 bit');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (52,'8 bit'),
	 (52,'16 bit'),
	 (52,'64 bit'),
	 (53,'myString'),
	 (53,'string'),
	 (53,'Txt'),
	 (54,'num x = 5'),
	 (43,'It is not an error to declare a variable to be one of the keywords'),
	 (54,'x = 5;'),
	 (54,'float x = 5;');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (55,'int x = 2.8f;'),
	 (55,'x = 2.8f;'),
	 (55,'byte x = 2.8f'),
	 (56,'getSize()'),
	 (56,'getLength()'),
	 (56,'len()'),
	 (43,'They can contain alphanumeric characters '),
	 (57,'<scripting>'),
	 (57,'<js>'),
	 (57,'<javascript>');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (58,'alertBox(''Hello World'');'),
	 (58,'msg(''Hello World'');'),
	 (58,'msgBox(''Hello World''); '),
	 (59,'if i = 5'),
	 (59,'if i = 5 then'),
	 (59,'if i == 5'),
	 (60,'if i <> 5  '),
	 (60,'if (i <> 5)'),
	 (60,'if i =! 5 then'),
	 (61,'for (i = 0; i <= 5)');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (61,'for i = 1 to 5'),
	 (61,'for (i <= 5; i++)'),
	 (62,'var colors = ''red'', ''green'', ''blue'''),
	 (62,'var colors = (1:''red'', 2:''green'', 3:''blue'')'),
	 (62,'var colors = 1 = (''red''), 2 = (''green''), 3 = (''blue'')'),
	 (63,'Math.rnd(7.25)'),
	 (63,'round(7.25)'),
	 (63,'rnd(7.25) '),
	 (64,'Math.ceil(x, y)'),
	 (64,'top(x, y)');
INSERT INTO public.question_incorrect_answers (question_qid,incorrect_answers) VALUES
	 (64,'ceil(x, y) '),
	 (65,'onmouseclick'),
	 (65,'onchange'),
	 (65,'onmouseover ');